(input_seqnames,) = glob_wildcards("data/{filename}.faa")

rule all:
	input:
		expand("intermediate/{name}.mafft_aligned.faa", name = input_seqnames)

rule mafft:
	input: "data/{seqname}.faa"
	output: "intermediate/{seqname}.mafft_aligned.faa"
	shell: "module load mafft &&"
			"mafft {input} > {output}"
	
	
